# Generated by Django 5.1.7 on 2025-03-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteHit',
        ),
    ]
